version: '2'
services:
  cars_shop-app:
    image: cars_shop
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cars_shop-postgresql:5432/cars_shop
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  cars_shop-postgresql:
    extends:
      file: postgresql.yml
      service: cars_shop-postgresql
